"""
src package - modularized coding agent.
"""

from src.config import (
    WORKDIR, client, MODEL, PRIMARY_MODEL, FALLBACK_MODEL,
    SKILLS_DIR, TRANSCRIPT_DIR, TOOL_RESULTS_DIR,
    DEFAULT_MAX_TOKENS, ESCALATED_MAX_TOKENS, MAX_RETRIES,
    MAX_CONSECUTIVE_529, MAX_RECOVERY_RETRIES, BASE_DELAY_MS,
    CONTEXT_LIMIT, KEEP_RECENT_TOOL_RESULTS, PERSIST_THRESHOLD,
    CONTINUATION_PROMPT, PROMPT, CLI_ACTIVE, MEMORY_DIR, MEMORY_INDEX,
    terminal_print
)

__all__ = [
    "WORKDIR", "client", "MODEL", "PRIMARY_MODEL", "FALLBACK_MODEL",
    "SKILLS_DIR", "TRANSCRIPT_DIR", "TOOL_RESULTS_DIR",
    "DEFAULT_MAX_TOKENS", "ESCALATED_MAX_TOKENS", "MAX_RETRIES",
    "MAX_CONSECUTIVE_529", "MAX_RECOVERY_RETRIES", "BASE_DELAY_MS",
    "CONTEXT_LIMIT", "KEEP_RECENT_TOOL_RESULTS", "PERSIST_THRESHOLD",
    "CONTINUATION_PROMPT", "PROMPT", "CLI_ACTIVE", "MEMORY_DIR", "MEMORY_INDEX",
    "terminal_print"
]